### ISSUE TITLE
How to load our own camera intrinsic matrix in webcam mode?

### ISSUE THREAD

**Issue by hcv1027** [vita-epfl/monoloco#18]
Is there a way to load my own camera intrinsic matrix in webcam mode?
From the source code, it looks like intrinsic matrix is computed by some default formula in `process.py`.
```python
def factory_for_gt(im_size, name=None, path_gt=None):
    ...
    except KeyError:
    dic_gt = None
    x_factor = im_size[0] / 1600
    y_factor = im_size[1] / 900
    pixel_factor = (x_factor + y_factor) / 2   # TODO remove and check it
    if im_size[0] / im_size[1] > 2.5:
        kk = [[718.3351, 0., 600.3891], [0., 718.3351, 181.5122], [0., 0., 1.]]  # Kitti calibration
    else:
        kk = [[1266.4 * pixel_factor, 0., 816.27 * x_factor],
                 [0, 1266.4 * pixel_factor, 491.5 * y_factor],
                 [0., 0., 1.]]  # nuScenes calibration
    print("Using a standard calibration matrix...")
```

**Comment by noah003** [comment]
The same question

**Comment by bertoni9** [comment]
Hello, 
Thanks for your interest! The 2 intrinsic matrices (kk) represent KITTI and nuScenes cameras. As a default, it will consider nuScenes camera parameters and scale them based on the image size captured from your computer.

If you wanna change the settings, you can modify the parameter **intrinsic_size** in `webcam.py` line 58.
```python
        intrinsic_size = [xx * 1.3 for xx in pil_image.size]
        kk, dict_gt = factory_for_gt(intrinsic_size)  # better intrinsics for mac camera
```
Or, if you know the intrinsics of your camera, you can just change the numbers in `factory_for_gt`. For now, I didn't implement anything to load them directly.

Hope it helps,
Lorenzo

**Comment by noah003** [comment]
> Hello,
> Thanks for your interest! The 2 intrinsic matrices (kk) represent KITTI and nuScenes cameras. As a default, it will consider nuScenes camera parameters and scale them based on the image size captured from your computer.
> 
> If you wanna change the settings, you can modify the parameter **intrinsic_size** in `webcam.py` line 58.
> 
> ```python
>         intrinsic_size = [xx * 1.3 for xx in pil_image.size]
>         kk, dict_gt = factory_for_gt(intrinsic_size)  # better intrinsics for mac camera
> ```
> 
> Or, if you know the intrinsics of your camera, you can just change the numbers in `factory_for_gt`. For now, I didn't implement anything to load them directly.
> 
> Hope it helps,
> Lorenzo

Thanks a lot!
