### ISSUE TITLE
Draw skeleton with pifpaf fails

### ISSUE THREAD

**Issue by patrick-llgc** [vita-epfl/monoloco#19]
Hi! First of all, thanks for your great work! The code quality is much higher than what I saw in other DL projects. Congratulations on the ICCV paper. 👍

I am trying to save the skeleton and keypoints prediction and I got the following error:

```
Ground-truth file not found
Using a standard calibration matrix...
Traceback (most recent call last):
  File "/Users/pliu/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/pliu/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pliu/github/monoloco/monoloco/run.py", line 157, in <module>
    main()
  File "/Users/pliu/github/monoloco/monoloco/run.py", line 100, in main
    predict.predict(args)
  File "/Users/pliu/github/monoloco/monoloco/predict.py", line 78, in predict
    factory_outputs(args, images_outputs, output_path, pifpaf_outputs, dic_out=dic_out, kk=kk)
  File "/Users/pliu/github/monoloco/monoloco/predict.py", line 105, in factory_outputs
    keypoint_painter.keypoints(ax, keypoint_sets)
```

The command I used is:

```python
python3 -m monoloco.run predict --glob /Users/pliu/Downloads/1000289627384.jpeg --output_types combined json keypoints skeleton --scale 2 --model data/models/monoloco-190513-1437.pkl  --z_max 50 --networks monoloco pifpaf
```

I looked at the arg list of `keypoint_painter.keypoints` and I am quite puzzled:

```
def keypoints(self, ax, keypoint_sets, *,
                  skeleton, scores=None, color=None, colors=None, texts=None):
```

Why there is a `*` in the middle, even before the positional argument of `skeleton`? How do I make saving keypoints and skeletons work?

Thanks for your help in advance!

**Comment by bertoni9** [comment]
Hello. Thank you a lot! 
Which error do you get exactly? Maybe you are not showing the last lines which indicate the type of error. I tried to reproduce your exact command with an image and for me it works.
It may be related with the latest version of openpifpaf, which version are you using? I suggest you to install 0.9.0 and see if it works. The keypoint function directly comes from openpifpaf code!
Lorenzo

**Comment by patrick-llgc** [comment]
@bertoni9 thanks so much for your reply!

Sorry the last line of the error message is indeed chopped off. 

```
TypeError: keypoints() missing 1 required keyword-only argument: 'skeleton'
```

Yes, I did look into the source code of pifpaf as well, and saw that they are the same as you mentioned. However, I believe the error stems from the fact that it may need the annotation file or prediction file to contain the format information about the skeleton. 

In my case, I just have an image that I took with my own camera, and do not have GT file. It seems that I have to specify skeleton argument to the painter?

**Comment by bertoni9** [comment]
If you don't have a GT file, it will use by default a standard calibration matrix and it is not a problem. The relative distances will be maintained (the absolute ones no). Which version of pifpaf do you have installed? Even if some functions are copied, monoloco code still uses the package openpifpaf.

**Comment by bertoni9** [comment]
I closed the issue. Feel free to open it again if you still have problems with it.
Thanks,
Lorenzo
