### ISSUE TITLE
The same error as #13 with more info provided

### ISSUE THREAD

**Issue by AbdelrahmanAEmam** [vita-epfl/monoloco#21]
I encountered the same issue and I am using Python 3
I cloned the repo then pip3 install -e '.[test, prep]'

![rsz_issue](https://user-images.githubusercontent.com/39004499/80283460-fb663b00-8717-11ea-9b24-c60d0ecef17f.png)

**Comment by bertoni9** [comment]
Hello,
Replied on the #13.
