### ISSUE TITLE
The objects is stored on the edges when using webcams

### ISSUE THREAD

**Issue by AbdelrahmanAEmam** [vita-epfl/monoloco#22]
First of all, you did such a GREAT work here. As for my issue I followed the instructions provided and downloaded the model/array files and folders as mentioned, but when I use the model with the webcam using <code>python3 -m monoloco.run predict --webcam --scale 0.2 --output_types combined --z_max 10 --checkpoint resnet50 --model data/models/monoloco-190719-0923.pkl</code> at first the camera detects me well, but when I try to move away from the FOV the **latest seen position is stored and I can still me detected but frozen (Keeps showing the last frame with the last pedestrian detected)!** Can you provide any help?

**Comment by bertoni9** [comment]
Hello, 
Thank you! In line 68 of webcam.py, VisualizerMonoloco received a new image only in case pifpaf detected a person. If you come back in the FOV, it should work again. Anyway, I changed the default to remove this frozen effect.
Best,
Lorenzo
