### ISSUE TITLE
"additional minimization objective" for epistemic uncertainty modeling

### ISSUE THREAD

**Issue by motokimura** [vita-epfl/monoloco#26]
Hi, thank you for sharing the code of your work!
I read your paper and got a question about epistemic uncertainty modeling.

In the [paper](https://arxiv.org/abs/1906.06059), you formulated `additional minimization objective` in eq. 5 for modeling the epistemic uncertainty.
How is this term used in training (or inference) phase?
I mean, is this term added to the loss to train the model?
I also looked into your code but could not figure out where this term was used.

Thank you in advance.

**Comment by bertoni9** [comment]
Hello, 
The epistemic uncertainty is based on the concept of [MC Dropout](https://arxiv.org/pdf/1506.02142.pdf). There is no difference in training apart from choosing an appropriate dropout rate. The loss does not change. At inference time, we sample multiple times to capture epistemic uncertainty and this corresponds to the additional minimization objective you mention. 

Hope it helps,
Lorenzo

**Comment by motokimura** [comment]
Thank you!

**Comment by hellojialee** [comment]
> Hello, The epistemic uncertainty is based on the concept of [MC Dropout](https://arxiv.org/pdf/1506.02142.pdf). There is no difference in training apart from choosing an appropriate dropout rate. The loss does not change. At inference time, we sample multiple times to capture epistemic uncertainty and this corresponds to the additional minimization objective you mention.
> 
> Hope it helps, Lorenzo

Hi, @bertoni9 , you said you sample multiple times to capture epistemic uncertainty. Dose equation (6) computed the sum of epistemic and aleatoric uncertainties? How to get the two uncertainties separated?
