### ISSUE TITLE
Using monoloco with Openpifpaf 0.11.6

### ISSUE THREAD

**Issue by kenshinli2000** [vita-epfl/monoloco#27]
Hi, I tried to integrate **openpifpaf 0.11.6** to monoloco as 0.11.6 is way faster than 0.9.0 but the monoloco results were way off. The key difference I observed from the 2 versions are 0.9.0 will provide all keypoint estimates even if certain joints are invisible or occluded whereas 0.11.6 will just return zero.

Can I confirm if this is the reason? Or if there are other reasons why the results are so off and if there are ways around it?

btw, awesome work done. I really like the quality of the projects.

**Comment by bertoni9** [comment]
Hi,
Thanks for the nice words. 
You are right, MonoLoco expects all joints to have a value, even the occluded ones (it learns to ignore them by their relative position and it helps for uncertainty). In openpifpaf 0.9 all the joints get a value if you use the **--force-complete-pose** flag. When you run monoloco.predict, the flag is set as True by default; if you run openpifpaf  alone, the default is False. The same flag should be in openpifpaf 0.11. and yes, this would solve the main problem. For optimal performances, you could also train MonoLoco with openpifpaf 0.11 annotations.

Best,
Lorenzo

**Comment by kenshinli2000** [comment]
I've tried to set the flag via
**openpifpaf.decoder.generator.cifcaf.CifCaf.force_complete = True**
but doesn't seem to work, as in some of the keypoints are still zero. Appreciate your advise.

thanks

**Comment by kenshinli2000** [comment]
> I've tried to set the flag via
> **openpifpaf.decoder.generator.cifcaf.CifCaf.force_complete = True**
> but doesn't seem to work, as in some of the keypoints are still zero. Appreciate your advise.
> 
> thanks

ok, I solved it.  the keypoint_threshold was previously set to non zero....
