### ISSUE TITLE
inverse of camera intrinsic matrix kk

### ISSUE THREAD

**Issue by kenshinli2000** [vita-epfl/monoloco#28]
Hi, I've 2 questions:

1. I understand that pixel_to_camera function is to back project the image keypoints to real world coordinates before feeding into the monoloco network to estimate z. But I'm having trouble reconciling the code with the formula in your research paper in section 4.1 eq (3), i.e. the order of the matrix multiplication between uv and the inverse of kk doesn't seem to match.

2. I'm looking at a use case of mounted camera at titled angle. I wonder if multiplying the inverse of the extrinsic camera matrix (rotation + translation) would improve the depth estimation. Have your team tested this scenario previously?

Appreciate your advise. Thanks

**Comment by kenshinli2000** [comment]
my bad.. I just realized torch.matmul(uv_padded, kk_1.t()) is the same as torch.matmul(kk_1, uv_padded.t()).t()...  So the formula is consistent

On question (2), appreciate any advise. thanks

**Comment by bertoni9** [comment]
Hi, I have never tried with such scenarios. The datasets for autonomous driving usually don't have tilted cameras. If you include the extrinsic it should be fine, but I cannot assist you more on that.
Best,
Lorenzo
