### ISSUE TITLE
Incorrect bird's eye view plot

### ISSUE THREAD

**Issue by keivan68** [vita-epfl/monoloco#29]
Hi,

Please see the attached images where the bird's eye view seems to be incorrect. I wonder whether this is because of the plot settings.

![028 png front](https://user-images.githubusercontent.com/42633168/86531102-4ff20900-be73-11ea-9739-d37df836837d.png)

![028 png bird](https://user-images.githubusercontent.com/42633168/86531101-4ff20900-be73-11ea-9e30-83290267f68a.png)

Thanks for your nice work.

**Comment by bertoni9** [comment]
Hi,
Yes, it's a plot setting. You can simply use the command *--z_max*  to choose the desired maximum distance for the bird's eye view. Anyway, this should be consistent with the frontal view, thanks for pointing it out.
