### ISSUE TITLE
Metric distance threshold

### ISSUE THREAD

**Issue by pmorerio** [vita-epfl/monoloco#32]
Hi first of all thanks for the great code.
I was wondering, is this

https://github.com/vita-epfl/monoloco/blob/aea6362ac29d696d0cb94b54e26998af4460304c/monoloco/predict_social.py#L190

a metric threshold of 2.5 meters?

**Comment by bertoni9** [comment]
Hello, thank you for your interest!
Yes, that's correct.
Best,
Lorenzo
