### ISSUE TITLE
) missing in argparse sub parsing

### ISSUE THREAD

**Issue by mvssanjay007** [vita-epfl/monoloco#33]
In line 76 , run.py the argparse is not closed using ). It might be typo but it sure does raise a error when executed directly.

**Comment by bertoni9** [comment]
Hello. Thanks for pointing it out. Are you talking about the master branch? Can you send me the error? In my case it works.
Thanks
Lorenzo

**Comment by mvssanjay007** [comment]
Sorry it's a wrong observation, There is no error in that file. I am extremely sorry for the inconvenience.
