### ISSUE TITLE
Kitti ground truth files

### ISSUE THREAD

**Issue by pavan321b** [vita-epfl/monoloco#35]
I am new to deep learning and CV. I am not able to find the exact Kitti ground truth files for the evaluation. Please Direct me towards the website where i can find it and please mention what files to be downloaded for kitti ground truth evaluation.
![monoloco kitti error msg](https://user-images.githubusercontent.com/60168980/91072639-6f2d3b80-e657-11ea-955a-59dead616d9e.PNG)

**Comment by bertoni9** [comment]
Hello,
The ground-truth files are the training labels of object data set.
Best,
Lorenzo
