### ISSUE TITLE
How to pass in the parameters of my own camera?

### ISSUE THREAD

**Issue by ChalsonLee** [vita-epfl/monoloco#37]
Thank you for your excellent work！I want to use my own camera for testing. From where in the code should I pass in my camera parameters and what parameters do I need to pass in?

**Comment by bertoni9** [comment]
Hello, Thank you! I should probably make this more accessible through a config file. For the moment, you can add your own parameters in `monoloco/network/process.py` at Line 50. You will need to change the parameters of the 3x3 Intrinsic matrix K

Hope it helps,
Lorenzo
