### ISSUE TITLE
nuScenes pre-trained model

### ISSUE THREAD

**Issue by vobecant** [vita-epfl/monoloco#39]
Hello,

first of all, thank you very much for your paper and for this repository. I see that you provide pre-trained models on google drive. Can you please tell me which model was pre-trained on the nuScenes dataset?

Thank you very much!

**Comment by bertoni9** [comment]
Hi,
Thank you for your interest! Together with the model there is a log file. In one of the first lines, it tells you which keypoints have been used to train the model. For example, the input file for **monoloco-190719-0923.pkl** is `data/arrays/joints-nuscenes_teaser-190717-1424.json` so the model has been trained using nuScenes teaser.

Hope it helps,
Lorenzo
