### ISSUE TITLE
Need help with generate ground truth file

### ISSUE THREAD

**Issue by Virion89** [vita-epfl/monoloco#41]
Lorenzo, good afternoon.
Help me figure out some points in the formation of data for monoloco to work on other cameras.

1. In the description of the Prediction section it is said that for more accurate results it is necessary to use the ground truth file. It can be obtained by following the instructions in the Preprocessing section.
But here it becomes unclear, tk. This section describes how to get the ground truth file from the KITTI / nuScenes dataset, but how do I get the ground truth file for my scene? Do we understand correctly that for this you need to collect your dataset from your scene and train your model on it. And already on your dataset you can get the ground truth file we need.

2. The project also talks about the use of a calibration matrix, which provides more accurate results. Your project uses a standard calibration matrix, which is designed for a resolution of 1600 * 900. But I have a video image with a resolution of 1280 * 720, due to which the results of monoloco work are very different from real ones, how can I get the calibration matrix for my image size?

**Comment by bertoni9** [comment]
Hello,
1. The ground-truth for nuScenes and KITTI has been obtained using LiDAR and with manual labelling. You can still use the pre-trained model on KITTI/nuScenes and use it to predict the distance on your custom dataset. 
2. Yes, the camera intrinsic parameters affect the prediction. To get accurate predictions you would need to use the calibration matrix of your camera (this includes image resolution as well as focal length), and substitute it inside the file network/process.py. You can find online how to construct a calibration matrix knowing the focal length and image resolution of the camera.

Hope it helps,
Lorenzo
