### ISSUE TITLE
confirmation for training instruction - MonoLocoPP

### ISSUE THREAD

**Issue by jbonobono** [vita-epfl/monoloco#45]
hello,
I get question during re-product trial  for MonoLocoPP's parameter.
followed by the training instruction, the training command line says that use "joints-kitti-201202-1743.json"
but the link attached(https://drive.google.com/file/d/1e-wXTO460ip_Je2NdXojxrOrJ-Oirlgh/view) points out  "names-kitti-200615-1022.json"

would you please confirm which json was used for your MonoLocoPP article?

thank you

**Comment by bertoni9** [comment]
Hello,
You are right, it is "joints-kitti", the other one is used for the ground-truth predictions mostly. I have updated the link in the Readme.
Thanks for letting me know

**Comment by jbonobono** [comment]
thanks for quick reply 
one more detail question
the name in training instruction command is "joints-kitti-201202-1743.json"
but the link file name is "joints-kitti-200604-0939.json"
do they have same contents? between 200604 & 201202
thank you
