### ISSUE TITLE
evaluation GT file

### ISSUE THREAD

**Issue by jbonobono** [vita-epfl/monoloco#48]
Hello 
now I am trying to do evaluation script followed by readme.md's instruction
according to the code,
it looks gt file is required according to line 52 of below file
( https://github.com/vita-epfl/monoloco/blob/main/monoloco/eval/generate_kitti.py )

would you please specify how can I get the gt file?

thank you

**Comment by bertoni9** [comment]
That's correct, you would need to download the ground-truth files from KITTI website. I updated the description in the README with the link to the website.
