### ISSUE TITLE
evaluation result question from monoloco++ article

### ISSUE THREAD

**Issue by jbonobono** [vita-epfl/monoloco#52]
Hello, 
thanks for the feedback now I could run train model followed by below command in instruction,
"python -m monoloco.run train --joints data/arrays/joints-kitti-201202-1743.json --save --monocular"
and could run eval mode as described in instruction
(although there were a few minor modification was needed to run it , but somehow there was result)

and when I compare the result I got vs in article TABLE I(https://arxiv.org/pdf/2009.00984.pdf)

I could check the difference as below

** from article TABLE 1
method         ||    Dataset   ||    NR of Instances  ||  ALE(Easy)    (Mod)        (Hard)         (ALL)   ||   ALA(<0.5m)   (1m)    (<2m)
MonoLoco++||   KITTI        ||     1799                  || 0.69[90%]  0.71[66%] 1.37[31%] 0.76[70%] || 37.4              53.2        63.6

** from self trial followed by instruction
method         ||    Dataset   ||    NR of Instances  ||  ALE(Easy)    (Mod)        (Hard)         (ALL)   ||   ALA(<0.5m)   (1m)    (<2m)
MonoLoco++||   KITTI        ||     1799                  || 0.65[80%]  0.61[52%] 1.07[17%] 0.67[58%] || 32.8              46.31       54.34

would you please confirm if the re-produce will have same result with TABLE I?

thank you

**Comment by jbonobono** [comment]
1 more question on upper
would you please specify the version of openpifpaf? which is used for article TABLE 1
considering the lower recall result I got, would like get same baseline 
thank you

**Comment by jbonobono** [comment]
Hello 
by following below steps , from data prep steps, (not using "joints-kitti-201202-1743.json")
I could get below result 
**1. data prep**
    openpifpaf json extraction from KITTI ("python -m openpifpaf.predict ~~")(openpifpaf version >0.12.1)
    training json creation("python -m monoloco.run prep ~~")
**2. train** ("python -m monoloco.run train~~)
**3. eva**l ("python -m monoloco.run eval~~)
**4. result** 
** result
method || Dataset || NR of Instances || ALE(Easy) (Mod) (Hard) (ALL) || ALA(<0.5m) (1m) (<2m)
MonoLoco++|| KITTI || 1391|| 0.62[83%] 0.74[55%] 1.49[20%] 0.71[61%] || 34.82 47.19 56.71

the result for ALE and ALE shows similar result with article but recall number and number of instance has diff (eg. 1799 vs 1391) 
hope I can have the root cause of it. let me get your diagnosis 

thank you

**Comment by bertoni9** [comment]
Hello,
Thanks for your interest!

With those joints I am able to reproduce the results of the article (I am working to add a table of results). I think the root cause is the PifPaf annotations. I used openpifpaf v0.12, and you can use the latest one. To increase the recall you can increase the image size and reduce the threshold of the instances. For example:

```sh
python -m openpifpaf.predict \
--glob <directory of KITTI images> \
--json-output <directory to save predictions> \
--checkpoint=shufflenetv2k30 \
--force-complete-pose \
--instance-threshold=0.05 --seed-threshold 0.05  --long-edge 2500
```
