### ISSUE TITLE
How to use output of PifPaf plugins (Crowdpose)

### ISSUE THREAD

**Issue by jagdishbhanushali** [vita-epfl/monoloco#54]
Hi,
Great Work with Monoloco and Pifpaf.

I wanted to train Monoloco on my custom datasets where I don't have all 17 keypoints. I'll be having 15 Keypoints and wanted to get depth out of them.  So I was thinking of using plugin in PifPaf for training and use those keypoints in Monoloco. 

How can I pass output of PIFPAF on custom dataset? Can you please help me how entire process will work.

Thanks,
Jagdish Bhanushali

**Comment by bertoni9** [comment]
Hi Jagdish,

Thank you for your interest!

To use a pre-trained monoloco model, you will need 17 joints.
One option is to run the crowdpose model in KITTI dataset and re-train monoloco using 15 joints. Alternatively, you can create a script to convert 15 keypoints into the expected 17 and use a pre-trained model, but I am not sure whether it would be feasible.

Regarding re-training monoloco on 15 keypoints:
For the moment, monoloco supports the preprocessing of KITTI and nuScenes dataset. You can add a preprocessing file for your custom dataset inside the folder `prep` and call it with the command `--dataset`. You would also need to change the input size into train/trainer.py, as for now only support 17 joints are supported (and train a new monoloco model). 

Hope it is clear. 

Best,
Lorenzo
