### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/shufflenet

### ISSUE THREAD

**Issue by aliraza0769** [vita-epfl/monoloco#55]
We tried to test the monoloco following code repo on google colab. 

`!python -m monoloco.run predict 'docs/002282.png' \
--path_gt '/content/monoloco/docs/names-kitti-200615-1022.json' \
-o '/content/monoloco' \
--long-edge 2500 \
--n_dropout 0`

We faced following error.  

**INFO:monoloco.predict:Downloading OpenPifPaf model in /root/.cache/torch/hub/checkpoints
Downloading...
From: https://drive.google.com/uc?id=1b408ockhh29OLAED8Tysd2yGZOo0N_SQ
To: /root/.cache/torch/hub/checkpoints/shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/monoloco/run.py", line 202, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/monoloco/run.py", line 131, in main
    predict(args)
  File "/usr/local/lib/python3.7/dist-packages/monoloco/predict.py", line 149, in predict
    args, dic_models = factory_from_args(args)
  File "/usr/local/lib/python3.7/dist-packages/monoloco/predict.py", line 104, in factory_from_args
    dic_models = download_checkpoints(args)
  File "/usr/local/lib/python3.7/dist-packages/monoloco/predict.py", line 64, in download_checkpoints
    DOWNLOAD(OPENPIFPAF_MODEL, pifpaf_model, quiet=False)
  File "/usr/local/lib/python3.7/dist-packages/gdown/download.py", line 90, in download
    f = open(tmp_file, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl9kpqm5tgtmp'**

**Comment by bertoni9** [comment]
Hello, 
It looks like an issue with google colab when trying to download the model from google drive. Below some options.
- have you tried to run it without google colab on a laptop (the code does not require a GPU)?
- Also in the FileNotFoundError the file name should end with **.pkl**, while here is followed by *9kpqm5tgtmp* which I have never seen.
- You can always download manually the model and then pass it as argument using `--checkpoint`. Just be sure to have the latest MonoLoco version installed (0.6).

Please let me know if any of them solves the issue, I'll leave it open for the moment.

Thanks,
Lorenzo

**Comment by aliraza0769** [comment]
Dear, We manually downloaded the model and uploaded keep it in the same folder of predict.py and run.py files. Then, we pass the model path argument with `--checkpoint`.  We manually uploaded the model on google colab. We added a modified code that gives the same error. 


`!python -m monoloco.run predict 'docs/002282.png' \
--path_gt '/content/monoloco/docs/names-kitti-200615-1022.json' \
--checkpoint '/content/shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl' \
-o '/content/monoloco' \
--long-edge 2500 \
--n_dropout 0`




The error is encountered as:

**INFO:monoloco.predict:Downloading model in /root/.cache/torch/hub/checkpoints
Downloading...
From: https://drive.google.com/uc?id=1krkB8J9JhgQp4xppmDu-YBRUxZvOs96r
To: /root/.cache/torch/hub/checkpoints/monoloco_pp-201203-1424.pkl
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/monoloco/monoloco/run.py", line 202, in <module>
    main()
  File "/content/monoloco/monoloco/run.py", line 131, in main
    predict(args)
  File "/content/monoloco/monoloco/predict.py", line 149, in predict
    args, dic_models = factory_from_args(args)
  File "/content/monoloco/monoloco/predict.py", line 104, in factory_from_args
    dic_models = download_checkpoints(args)
  File "/content/monoloco/monoloco/predict.py", line 88, in download_checkpoints
    DOWNLOAD(path, model, quiet=False)
  File "/usr/local/lib/python3.7/dist-packages/gdown/download.py", line 90, in download
    f = open(tmp_file, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/monoloco_pp-201203-1424.pklswxdc6nftmp'**

**Comment by aliraza0769** [comment]
```!python -m monoloco.run predict 'docs/002282.png' \
--path_gt '/content/monoloco/docs/names-kitti-200615-1022.json' \
--checkpoint pifpaf \
-o '/content/monoloco' \
--long-edge 2500 \
--n_dropout 0```

gives the following error:


INFO:monoloco.predict:Downloading OpenPifPaf model in /root/.cache/torch/hub/checkpoints
Downloading...
From: https://drive.google.com/uc?id=1b408ockhh29OLAED8Tysd2yGZOo0N_SQ
To: /content/monoloco/pifpaf
129MB [00:00, 175MB/s]
INFO:monoloco.predict:Downloading model in /root/.cache/torch/hub/checkpoints
Downloading...
From: https://drive.google.com/uc?id=1krkB8J9JhgQp4xppmDu-YBRUxZvOs96r
To: /root/.cache/torch/hub/checkpoints/monoloco_pp-201203-1424.pkl
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/monoloco/monoloco/run.py", line 202, in <module>
    main()
  File "/content/monoloco/monoloco/run.py", line 131, in main
    predict(args)
  File "/content/monoloco/monoloco/predict.py", line 149, in predict
    args, dic_models = factory_from_args(args)
  File "/content/monoloco/monoloco/predict.py", line 104, in factory_from_args
    dic_models = download_checkpoints(args)
  File "/content/monoloco/monoloco/predict.py", line 88, in download_checkpoints
    DOWNLOAD(path, model, quiet=False)
  File "/usr/local/lib/python3.7/dist-packages/gdown/download.py", line 90, in download
    f = open(tmp_file, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/monoloco_pp-201203-1424.pkl500_20watmp'

**Comment by bertoni9** [comment]
Yes, it's the same problem you had with pifpaf model but now with monoloco model. Google colab adds a string (bold) at the end of the name. 

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/checkpoints/monoloco_pp-201203-1424.pkl**swxdc6nftmp**

You can just rename the file  or you can also download manually the monoloco++ model and call it with `--model <model_path>` (in addition to the argument `--checkpoint` for the openpifpaf model).

**Comment by wear-Electroniks** [comment]
Dear Lorenzo, 

We tested the below code on PC. We manually downloaded the shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl  file and keep it in  /monoloco/docs folder.  Then, tried to run below code.

`python -m monoloco.run predict /monoloco/docs/002282.png --path_gt /monoloco/docs/names-kitti-200615-1022.json --checkpoint oenpifpaf -o /monoloco --model /monoloco/docs/shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl --long-edge 2500 --n_dropout 0`    


and the model started downloading but gives following error in a while. 


INFO:monoloco.predict:Downloading OpenPifPaf model in C:\Users\abc/.cache\torch\hub\checkpoints
Downloading...
From: https://drive.google.com/uc?id=1b408ockhh29OLAED8Tysd2yGZOo0N_SQ
To: C:\Users\abc\crowd_Counting\monoloco\oenpifpaf
129MB [03:29, 615kB/s]
Traceback (most recent call last):
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 202, in <module>
    main()
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 131, in main
    predict(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 149, in predict
    args, dic_models = factory_from_args(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 104, in factory_from_args
    dic_models = download_checkpoints(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 69, in download_checkpoints
    assert os.path.exists(args.model), "Model path not found"
AssertionError: Model path not found

**Comment by wear-Electroniks** [comment]
After testing the below code ,

 ` python -m monoloco.run predict /monoloco/docs/002282.png --path_gt /monoloco/docs/names-kitti-200615-1022.json --checkpoint oenpifpaf -o /monoloco --model C:\Users\abc\crowd_Counting\monoloco\oenpifpaf --long-edge 2500 --n_dropout 0`


_we got RuntimeError: Error(s) in loading state_dict for LocoModel:_ 


**INFO:monoloco.predict:Force complete pose is active
Traceback (most recent call last):
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 202, in <module>
    main()
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 131, in main
    predict(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 153, in predict
    net = Loco(
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\network\net.py", line 77, in __init__
    self.model.load_state_dict(torch.load(model_path, map_location=lambda storage, loc: storage))
  File "C:\Users\abc\crowd_Counting\crowd_env\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LocoModel:
        Missing key(s) in state_dict: "w1.weight", "w1.bias", "batch_norm1.weight", "batch_norm1.bias", "batch_norm1.running_mean", "batch_norm1.running_var", "linear_stages.0.w1.weight", "linear_stages.0.w1.bias", "linear_stages.0.batch_norm1.weight", "linear_stages.0.batch_norm1.bias", "linear_stages.0.batch_norm1.running_mean", "linear_stages.0.batch_norm1.running_var", "linear_stages.0.w2.weight", "linear_stages.0.w2.bias", "linear_stages.0.batch_norm2.weight", "linear_stages.0.batch_norm2.bias", "linear_stages.0.batch_norm2.running_mean", "linear_stages.0.batch_norm2.running_var", "linear_stages.1.w1.weight", "linear_stages.1.w1.bias", "linear_stages.1.batch_norm1.weight", "linear_stages.1.batch_norm1.bias", "linear_stages.1.batch_norm1.running_mean", "linear_stages.1.batch_norm1.running_var", "linear_stages.1.w2.weight", "linear_stages.1.w2.bias", "linear_stages.1.batch_norm2.weight", "linear_stages.1.batch_norm2.bias", "linear_stages.1.batch_norm2.running_mean", "linear_stages.1.batch_norm2.running_var", "linear_stages.2.w1.weight", "linear_stages.2.w1.bias", "linear_stages.2.batch_norm1.weight", "linear_stages.2.batch_norm1.bias", "linear_stages.2.batch_norm1.running_mean", "linear_stages.2.batch_norm1.running_var", "linear_stages.2.w2.weight", "linear_stages.2.w2.bias", "linear_stages.2.batch_norm2.weight", "linear_stages.2.batch_norm2.bias", "linear_stages.2.batch_norm2.running_mean", "linear_stages.2.batch_norm2.running_var", "w2.weight", "w2.bias", "w3.weight", "w3.bias", "batch_norm3.weight", "batch_norm3.bias", "batch_norm3.running_mean", "batch_norm3.running_var", "w_aux.weight", "w_aux.bias", "w_fin.weight", "w_fin.bias".
        Unexpected key(s) in state_dict: "model", "epoch", "meta".**

**Comment by wear-Electroniks** [comment]
The little modified code 

`python -m monoloco.run predict docs/002282.png --model docs/shufflenetv2k30-201104-224654-cocokp-d75ed641.pkl --path_gt docs/names-kitti-200615-1022.json --checkpoint oenpifpaf -o /monoloco --long-edge 2500 --n_dropout 0`


gives below error

**INFO:monoloco.predict:Downloading OpenPifPaf model in C:\Users\abc/.cache\torch\hub\checkpoints
Downloading...
From: https://drive.google.com/uc?id=1b408ockhh29OLAED8Tysd2yGZOo0N_SQ
To: C:\Users\abc\crowd_Counting\monoloco\oenpifpaf
129MB [01:16, 1.69MB/s]
INFO:monoloco.predict:Force complete pose is active
Traceback (most recent call last):
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 202, in <module>
    main()
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 131, in main
    predict(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 153, in predict
    net = Loco(
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\network\net.py", line 77, in __init__
    self.model.load_state_dict(torch.load(model_path, map_location=lambda storage, loc: storage))
  File "C:\Users\abc\crowd_Counting\crowd_env\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LocoModel:
        Missing key(s) in state_dict: "w1.weight", "w1.bias", "batch_norm1.weight", "batch_norm1.bias", "batch_norm1.running_mean", "batch_norm1.running_var", "linear_stages.0.w1.weight", "linear_stages.0.w1.bias", "linear_stages.0.batch_norm1.weight", "linear_stages.0.batch_norm1.bias", "linear_stages.0.batch_norm1.running_mean", "linear_stages.0.batch_norm1.running_var", "linear_stages.0.w2.weight", "linear_stages.0.w2.bias", "linear_stages.0.batch_norm2.weight", "linear_stages.0.batch_norm2.bias", "linear_stages.0.batch_norm2.running_mean", "linear_stages.0.batch_norm2.running_var", "linear_stages.1.w1.weight", "linear_stages.1.w1.bias", "linear_stages.1.batch_norm1.weight", "linear_stages.1.batch_norm1.bias", "linear_stages.1.batch_norm1.running_mean", "linear_stages.1.batch_norm1.running_var", "linear_stages.1.w2.weight", "linear_stages.1.w2.bias", "linear_stages.1.batch_norm2.weight", "linear_stages.1.batch_norm2.bias", "linear_stages.1.batch_norm2.running_mean", "linear_stages.1.batch_norm2.running_var", "linear_stages.2.w1.weight", "linear_stages.2.w1.bias", "linear_stages.2.batch_norm1.weight", "linear_stages.2.batch_norm1.bias", "linear_stages.2.batch_norm1.running_mean", "linear_stages.2.batch_norm1.running_var", "linear_stages.2.w2.weight", "linear_stages.2.w2.bias", "linear_stages.2.batch_norm2.weight", "linear_stages.2.batch_norm2.bias", "linear_stages.2.batch_norm2.running_mean", "linear_stages.2.batch_norm2.running_var", "w2.weight", "w2.bias", "w3.weight", "w3.bias", "batch_norm3.weight", "batch_norm3.bias", "batch_norm3.running_mean", "batch_norm3.running_var", "w_aux.weight", "w_aux.bias", "w_fin.weight", "w_fin.bias".
        Unexpected key(s) in state_dict: "model", "epoch", "meta".**

**Comment by bertoni9** [comment]
You are mixing the models in the commands. The shufflenet model is for pifpaf, not for monoloco. As you are trying it on the PC try to follow the commands in the README. This should solve the problem.

**Comment by wear-Electroniks** [comment]
Dear Lorenzo, 

Thanks for help. We successfully tested your designed Monoloco++ (openpifpaf model), But it gives following attribute error when we used the monoloco++ model for social distancing.

`python -m monoloco.run predict docs/frame0032.jpg --model docs/monoloco_pp-210422-1601.pkl --checkpoint oenpifpaf --social_distance --output_types front bird`


**INFO:monoloco.predict:Downloading OpenPifPaf model in C:\Users\abc/.cache\torch\hub\checkpoints
Downloading...
From: https://drive.google.com/uc?id=1b408ockhh29OLAED8Tysd2yGZOo0N_SQ
To: C:\Users\abc\crowd_Counting\monoloco\oenpifpaf
129MB [03:19, 645kB/s]
INFO:monoloco.predict:Force complete pose is active
INFO:openpifpaf.decoder.cifcaf:9 annotations: [17, 16, 16, 13, 11, 11, 10, 14, 6]
INFO:monoloco.predict:batch 0: docs/frame0032.jpg
0 image frame0032.jpg saved as docs\out_frame0032.jpg
INFO:monoloco.network.process:Using a standard calibration matrix...
INFO:monoloco.predict:Prediction with MonoLoco++
INFO:monoloco.predict:docs\out_frame0032.jpg
Traceback (most recent call last):
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abc\pyver\py391\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 202, in <module>
    main()
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\run.py", line 131, in main
    predict(args)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 231, in predict
    factory_outputs(args, pifpaf_outs, dic_out, output_path, kk=kk)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\predict.py", line 257, in factory_outputs
    show_social(args, pifpaf_outs['image'], output_path, pifpaf_outs['left'], dic_out)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\activity.py", line 132, in show_social
    with image_canvas(image_t,
  File "C:\Users\abc\pyver\py391\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\abc\crowd_Counting\monoloco\monoloco\visuals\pifpaf_show.py", line 55, in image_canvas
    image_2 = ndimage.gaussian_filter(image, sigma=2.5)
AttributeError: 'NoneType' object has no attribute 'gaussian_filter'**

**Comment by bertoni9** [comment]
Closing it. Feel free to re-open it, if you still have problems.

**Comment by bertoni9** [comment]
Hello, I have found the problem with google collab. It didn't create the torch directory to save the model. Now it's fixed.

**Comment by aliraza0769** [comment]
Hello dear Lorenzo,



We tried the below code on the modified repository.

"!python3 -m monoloco.run predict '/content/monoloco/docs/002282.png'
 \--path_gt '/content/monoloco/names-kitti-200615-1022.json' \-o
'/content/monoloco' \--long-edge 2500 \--n_dropout 0"


We got the below error. It is an import error this time.

'Traceback (most recent call last):
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec) File "/usr/lib/python3.7/runpy.py", line 85, in
_run_code exec(code, run_globals) File "/content/monoloco/monoloco/run.py",
line 213, in <module> main() File "/content/monoloco/monoloco/run.py", line
141, in main from .predict import predict File
"/content/monoloco/monoloco/predict.py", line 21, in <module> from
openpifpaf.predict import processor_factory, preprocess_factory
ImportError: cannot import name 'processor_factory' from
'openpifpaf.predict'
(/usr/local/lib/python3.7/dist-packages/openpifpaf/predict.p'

The functions named *processor_factory, preprocess_factory *are not defined
in openpifpaf.predict module.

Looking forward to hearing from you. Thanks


Best Regards,
