### ISSUE TITLE
How to apply monoloco to each frame of a video?

### ISSUE THREAD

**Issue by Christoph9402** [vita-epfl/monoloco#57]
Hello,
I am trying to use monoloco for a video file. At the moment my code has the following simple structure:
<img width="619" alt="Screenshot 2021-05-02 141142" src="https://user-images.githubusercontent.com/62546080/116812691-5a8f3480-ab50-11eb-81b1-65256852bdd6.png">
I would like to call monoloco where it says "detect pose". I am now looking of a way to apply monoloco to each frame of the video and it should be as fast as possible. Thats why I tried for example loading the model before looping through each frame of the video, which did not work. Is there an easy way of calling monoloco within my script for each frame?  I am looking fo a similar way like the openpifpaf api described [here](https://openpifpaf.github.io/predict_api.html). I dont want to save each frame as a .png file and then use monoloco. Thanks :)

**Comment by bertoni9** [comment]
Hello,

Thanks for your interests. 
Currently, we don't have a video option already implemented (feel free to create a pull request if you are interested in making one).

Two ideas for that:
- A new [Webcam feature](https://github.com/vita-epfl/monoloco/pull/46) is almost ready (CC: @charlesbvll). You can start from this code to apply monoloco on videos.
- check OpenPifpaf repository. It has a [video command](https://github.com/openpifpaf/openpifpaf/blob/main/openpifpaf/video.py), which you could extend for monoloco.

Hope it helps,
Lorenzo
