### ISSUE TITLE
Problem about pifpaf model

### ISSUE THREAD

**Issue by seonhoon1002** [vita-epfl/monoloco#60]
First of all, I'm thank for your work

But I have a problem to run your predict code

I was faced this error

assert DOWNLOAD is not None, "install gdown to download pifpaf model, or pass it as --checkpoint"
AssertionError: install gdown to download pifpaf model, or pass it as --checkpoint

How can I solve it?

**Comment by bertoni9** [comment]
Hello, the warning is telling to `pip install gdown` to being able to download the model.
 I'll make it more explicit.
