### ISSUE TITLE
Installing monoloco on Jetson

### ISSUE THREAD

**Issue by daodao9801** [vita-epfl/monoloco#61]
Hi,

I am new to the area and tried to install monoloco as recommended by running,
`pip3 install monoloco`
However, it droped error saying,
"Collecting torch>=1.7.1 (from openpifpaf>=v0.12.1->monoloco)
  Could not find a version that satisfies the requirement torch>=1.7.1 (from openpifpaf>=v0.12.1->monoloco) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch>=1.7.1 (from openpifpaf>=v0.12.1->monoloco)
"

I am running the command on my Jetson Xavier NX module with pytorch 1.8.0 installed,
when I run `pip3 freeze`, torch=1.8.0 is shown and `import torch` in the python3 is successful.

I guess that means the torch version is satisfied, right?
Could you please give some advice on how to fix this?
Thanks in advance.

**Comment by bertoni9** [comment]
Hello, 

It is a weird error, indeed.  It seems a problem related to torch, can you create a new empty virtulalenv and just run `pip3 install monoloco`? You can also try to install openpifpaf with `pip3 install openpifpaf` and see if you get the same error.

**Comment by daodao9801** [comment]
> Hello,
> 
> It is a weird error, indeed. It seems a problem related to torch, can you create a new empty virtulalenv and just run `pip3 install monoloco`? You can also try to install openpifpaf with `pip3 install openpifpaf` and see if you get the same error.

Hi Lorenzo,

Thanks for your quick reply. I haven`t tried the virtulalenv yet but the `pip3 install openpifpaf`returned the same error. I checked the openpifpaf repo and found a similiar problem [issue](https://github.com/openpifpaf/openpifpaf/issues/141) [suggestion](https://github.com/mindsdb/lightwood/issues/11#issuecomment-517667155)
Sorry I  have some difficulty in understanding the solution, would you mind explain in detail a little bit?

If it is something related to torch, I guess the problem is less likely to be solved. Since Jetson Embedded modules can only suit torch for [aarch64 edition](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048),  some compatibiity issue may be unsolvable unless their developers can help.

**Comment by bertoni9** [comment]
Hello, 
Unfortunately, I can't help on that at the moment. I'll leave the issue open and changed the title. I am sure you'll find something as this is related to torch mainly.

**Comment by daodao9801** [comment]
Hi,

I gave up the migration on Jetson Xavier since the tasks are finished on PC now and no longer needs real-time processing.
As for the issue itself, I believe that the future aarch64 torch edition might solve it automatically since it is just something about compatibility.
Thanks again for your help and I guess it would be fine if you thought this could be closed.

Best,
Pheo

**Comment by bertoni9** [comment]
Ok, thanks for letting me know!

**Comment by sergesaaybi** [comment]
Hello, I was also facing the same issue on the Jetson nano.
The steps I followed to fix it were:
- I installed pytorch v1.8.0 and torchvision from this link: https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048
- I then installed monoloco and openpifpaf using: `sudo pip3 install monoloco`  (based on a similar issue with another library which was solved this way: https://forums.developer.nvidia.com/t/error-installing-pytorch-pretrained-bert/82274)
