### ISSUE TITLE
How to generate annotation file for custom dataset

### ISSUE THREAD

**Issue by aliraza0769** [vita-epfl/monoloco#64]
We are trying to evaluate the pre-trained model on our custom dataset. How do we generate an annotation file for each image of the custom dataset?

Thanks.

**Comment by aliraza0769** [comment]
We generated an annotation file for our custom image dataset using the below command 


`!python3 -m openpifpaf.predict \
--glob "/content/monoloco/4901_002220.jpg" \
--json-output '/content/monoloco' \
--checkpoint=shufflenetv2k30 \
--instance-threshold=0.05 --seed-threshold 0.05 --force-complete-pose`


then, we run the following code to combine all individual json files to form a single json file using the below command. 

`!python3 -m monoloco.run prep \--dir_ann '/content/monoloco/kitti'`

and we got the following error for not giving a path to ground truth files.

**Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/monoloco/monoloco/run.py", line 213, in <module>
    main()
  File "/content/monoloco/monoloco/run.py", line 151, in main
    prep = PreprocessKitti(args.dir_ann, mode=args.mode, iou_min=args.iou_min)
  File "/content/monoloco/monoloco/prep/preprocess_kitti.py", line 61, in __init__
    assert os.path.isdir(self.dir_gt), "Ground truth directory not found"
AssertionError: Ground truth directory not found**.


How we generate ground truth files for images of custom dataset. Thanks.

**Comment by bertoni9** [comment]
Hello, 
to evaluate it you can modify the file monoloco/eval/generate_kitti.py that run the network over the given images and converts the annotation in KITTI format. The file will monoloco/eval/eval_kitti.py will then load the annotations and run the evaluation.
Please take a look also at the evaluation section in the Readme.

Hope it helps,
Lorenzo
