### ISSUE TITLE
about the predict demo

### ISSUE THREAD

**Issue by ShiMinghao0208** [vita-epfl/monoloco#70]
When I run the demo command:
`python3 -m monoloco.run predict docs/frame0032.jpg \
--activities social_distance --output_types front bird 
`
there is a loader_workers error, then I just modify the args.loader_workers=1 to test,there is a batch_size arg error.
what happened, about the code installing is successful, I run the test code of monoloco.run.
![QQ图片20210725111044](https://user-images.githubusercontent.com/53176521/126886422-e898b269-a7dd-4387-9148-dca98abbd9a1.png)

**Comment by bertoni9** [comment]
Hi, can you make sure you have installed openpifpaf>=v0.12.10'?

**Comment by sergesaaybi** [comment]
Hello, I am also facing the same "loader_workers error" when running monoloco's demo command on the nvidia Jetson.  I also made sure that the newest version of openpifpaf was used.

**Comment by sergesaaybi** [comment]
> Hello, I am also facing the same "loader_workers error" when running monoloco's demo command on the nvidia Jetson. I also made sure that the newest version of openpifpaf was used.

I got it to work from my end by installing openpifpaf==0.12.12 and monoloco==0.7.4.4

**Comment by bertoni9** [comment]
Great! Closing it, feel free to re-open it if you still have issues
