### ISSUE TITLE
About distortion

### ISSUE THREAD

**Issue by seonhoon1002** [vita-epfl/monoloco#71]
I have a question about distortion.

In KITTI dataset, they use rectified images which were erased distortion like radial.

But in your work, there isn't mention about distortion.

So, why did you use uncalibrated image?

Is it minor things to ignore?

**Comment by bertoni9** [comment]
Hello, I am not sure what do you mean, where do I use uncalibrated images? In general yes, the network does not take of distortion so it's better to undistort them first.
