### ISSUE TITLE
detection on closer distances

### ISSUE THREAD

**Issue by golnazhabibi3** [vita-epfl/monoloco#72]
Thanks for your great work. When I run the algorithm on my images (from Realsense) or even with webcam, it seems its depth estimation (specially for images from the realsense) is incorrect and it is usually a high value. Do you know if I have set any parameters?Thanks!

**Comment by bertoni9** [comment]
Hi! Yes, this may depends from the intrinsic parameters of the camera, which you need to update with the ones from Realsense. Please check #37 
Feel free to re-open it if it's something else.
