### ISSUE TITLE
How do you learn body orientation?

### ISSUE THREAD

**Issue by seonhoon1002** [vita-epfl/monoloco#73]
Thanks for your great work

I want to study further in body orientation, but I can't find how does your model learns body orientation in your papers.

So could you tell me how do you learn body orientation in your model

**Comment by bertoni9** [comment]
Hi, 
I refer to the body orientation in the article [Perceiving Humans](https://arxiv.org/pdf/2009.00984.pdf), in Section Method-->output. In summary, we predict the viewpoint angle with a regression, and parametrize it as [sin(x), cos(x)] to avoid discontinuity.
