### ISSUE TITLE
Problem about --keypoints command

### ISSUE THREAD

**Issue by 18-0217DaisukeHayashi** [vita-epfl/monoloco#74]
I apologize for my ignorance.
If you try to use --keypoints, you will get the following error.

`ValueError: cannot convert float NaN to integer`

It was running until two months ago.

Here is the log.

python3 -m monoloco.run predict sample.jpg --mode keypoints

`
INFO:monoloco.predict:Force complete pose is active

INFO:openpifpaf.predictor:neural network device: cuda (CUDA available: True, count: 1)
INFO:openpifpaf.decoder.cifcaf:5 annotations: [12, 12, 11, 6, 0]
INFO:openpifpaf.predictor:batch 0: sample.jpg
0 image sample.jpg saved as out_sample.jpg
/home/fuchsia/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/fuchsia/.local/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/monoloco/run.py", line 218, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/monoloco/run.py", line 147, in main
    predict(args)
  File "/usr/local/lib/python3.6/dist-packages/monoloco/predict.py", line 259, in predict
    avg_time = int(np.mean(timing))
ValueError: cannot convert float NaN to integer
`

**Comment by bertoni9** [comment]
Hello, can you make sure you have the latest version installed?  In the main brand, the code does:
```
    if args.mode != 'keypoints':
        timing = np.array(timing)
        avg_time = int(np.mean(timing))
        std_time = int(np.std(timing))
```
